Repository jlabeit/react-here-maps, pull requests merged in 2019-08, with the labels that each got.

#29 Feature/rerender marker on data change
  package-lock.json
  package.json
  src/Marker.tsx
  tsconfig.json
Labels: ready for review

#30 Version 1.5.2
  CHANGELOG.md
  package.json
Labels: version

#31 Release/1.5.2
  CHANGELOG.md
  package-lock.json
  package.json
  src/HEREMap.tsx
  src/Marker.tsx
  tsconfig.json
Labels: release

#32 Add missing null check
  src/Marker.tsx
Labels: ready for review

#33 Version 1.5.3
  CHANGELOG.md
  package.json
Labels: version

#34 Release/1.5.3
  CHANGELOG.md
  package.json
  src/Marker.tsx
Labels: release

#35 Prevent needlessly removing and readding markers
  src/Marker.tsx
Labels: ready for review

#36 Fix/re render markers no map mounted
  src/Marker.tsx
Labels: ready for review
